- id: '1646825292818'
  alias: config push to git
  description: ''
  trigger:
  - platform: time
    at: '18:30:00'
  condition: []
  action:
  - service: hassio.addon_stdin
    data:
      addon: a0d7b954_ssh
      input: /config/ha_gitpush.sh
  mode: single
